version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node

    steps:
      - checkout
      - run: sudo apt update

  deploy:
    machine:
      image: circleci/classic:edge
    steps:
      - add_ssh_keys:
          fingerprints:
            - "5f:bb:8e:67:78:cb:14:43:b6:8a:ce:7e:72:b2:6e:4e"
      - run: ssh ${USER_NAME}@${HOST_NAME} 'cd /var/www/aws-node/ && git pull origin master'

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
